### ISSUE TITLE
Athena scan throws an error on the athena extractor instantiation

### ISSUE THREAD

**Issue by patrick-mckinley** [tokern/piicatcher#155]
When running piicatcher both as an API in a python script and directly from the command line i get the following:

Running:
```
piicatcher scan athena --region-name eu-west-2 --s3-staging-dir s3://some-bucket-name/piicatcher --name athena --aws-access-key-id $AWS_ACCESS_KEY_ID --aws-secret-access-key $AWS_SECRET_ACCESS_KEY
```

i get:
```
Traceback (most recent call last):
  File "./.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "./.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "./.venv/lib/python3.8/site-packages/pyathena/util.py", line 306, in _wrapper
    return wrapped(*args, **kwargs)
  File "./.venv/lib/python3.8/site-packages/pyathena/cursor.py", line 81, in execute
    raise OperationalError(query_execution.state_change_reason)
pyathena.error.OperationalError: SYNTAX_ERROR: line 2:9: Column 'none' cannot be resolved

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./.venv/bin/piicatcher", line 8, in <module>
    sys.exit(app())
  File "./.venv/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "./.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "./.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "./.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "./.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "./.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "./.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "./.venv/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "./.venv/lib/python3.8/site-packages/piicatcher/cli.py", line 358, in athena
    op = scan_athena(
  File "./.venv/lib/python3.8/site-packages/piicatcher/api.py", line 410, in scan_athena
    return scan_database(
  File "./.venv/lib/python3.8/site-packages/piicatcher/api.py", line 122, in scan_database
    raise e
  File "./.venv/lib/python3.8/site-packages/piicatcher/api.py", line 80, in scan_database
    scanner.scan()
  File "./.venv/lib/python3.8/site-packages/dbcat/catalog/db.py", line 133, in scan
    extractor.init(Scoped.get_scoped_conf(self._conf, extractor.get_scope()))
  File "./.venv/lib/python3.8/site-packages/databuilder/extractor/athena_metadata_extractor.py", line 58, in init
    self._alchemy_extractor = sql_alchemy_extractor.from_surrounding_config(conf, self.sql_stmt)
  File "./.venv/lib/python3.8/site-packages/databuilder/extractor/sql_alchemy_extractor.py", line 102, in from_surrounding_config
    ae.init(c)
  File "./.venv/lib/python3.8/site-packages/databuilder/extractor/sql_alchemy_extractor.py", line 40, in init
    self._execute_query()
  File "./.venv/lib/python3.8/site-packages/databuilder/extractor/sql_alchemy_extractor.py", line 65, in _execute_query
    self.results = self.connection.execute(self.extract_sql)
  File "./.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "./.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "./.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "./.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "./.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "./.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "./.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "./.venv/lib/python3.8/site-packages/pyathena/util.py", line 306, in _wrapper
    return wrapped(*args, **kwargs)
  File "./.venv/lib/python3.8/site-packages/pyathena/cursor.py", line 81, in execute
    raise OperationalError(query_execution.state_change_reason)
sqlalchemy.exc.OperationalError: (pyathena.error.OperationalError) SYNTAX_ERROR: line 2:9: Column 'none' cannot be resolved
[SQL:
    SELECT
        None as cluster, table_schema as schema, table_name as name, column_name as col_name,
        data_type as col_type,ordinal_position as col_sort_order,
        comment as col_description, extra_info as extras from information_schema.columns

        ORDER by cluster, schema, name, col_sort_order ;
    ]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

i am running versions `0.17.3` on macosx 
```
❯ ./.venv/bin/piicatcher --version
0.17.3
Usage: piicatcher [OPTIONS] COMMAND [ARGS]...
Try 'piicatcher --help' for help.

Error: Missing command.
```

As a seperate issue i seem to get an error when i manually run that SQL in the athena termincal minus the "None as cluster" clause. but i think that's more around AWS than piicatcher.

**Comment by vrajat** [comment]
This should be solved if you add `--database <db name>`. I'll keep this issue open to improve the error message. 
Also, can you help me understand how you think about database and schema w.r.t Athena? In Postgres and MySQL, a database contains schemata which in turn contain tables. 

In case of Athena, database and schema are interchangeable. So looks like piicatcher should ignore database. Is my thinking right?

**Comment by patrick-mckinley** [comment]
Adding `--database` to it results in another error:
```
Usage: piicatcher scan athena [OPTIONS]
Try 'piicatcher scan athena --help' for help.

Error: No such option: --database
```

What is the `cluster` key supposed to achieve in that query?

I mean, you're right about schema and database being interchangable though - so that does make sense.

**Comment by vrajat** [comment]
I plan to remove it. It is a field required by a library piicatcher depends on. I plan to fill a dummy value there. It is not used by athena code anyway.

**Comment by vrajat** [comment]
I've released `0.17.4`. please give that a try.

**Comment by patrick-mckinley** [comment]
Thanks, that works - except for the `--database` argument not being accepted.
I manually tweaked the athena information_schema query to put the `{catalog_source}` in quotes as a literal, and that works.

Not sure what the fix for adding in the `--database` flag is here.

https://github.com/tokern/piicatcher/issues/155#issuecomment-979299260

**Comment by vrajat** [comment]
Ignore my comment on --database. It is not required. It should work without it.

**Comment by patrick-mckinley** [comment]
ah cool.

There's still an issue, which is basically the same as above (only instead of "None" it's now the value of the "name" parameter)

```
❯ ./.venv/bin/piicatcher scan athena --region-name eu-west-2 --s3-staging-dir s3://s3-bucket/piicatcher --name athena
Traceback (most recent call last):
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/pyathena/util.py", line 306, in _wrapper
    return wrapped(*args, **kwargs)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/pyathena/cursor.py", line 81, in execute
    raise OperationalError(query_execution.state_change_reason)
pyathena.error.OperationalError: SYNTAX_ERROR: line 2:9: Column 'athena' cannot be resolved

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./.venv/bin/piicatcher", line 8, in <module>
    sys.exit(app())
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/piicatcher/cli.py", line 358, in athena
    op = scan_athena(
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/piicatcher/api.py", line 409, in scan_athena
    return scan_database(
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/piicatcher/api.py", line 122, in scan_database
    raise e
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/piicatcher/api.py", line 80, in scan_database
    scanner.scan()
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/dbcat/catalog/db.py", line 133, in scan
    extractor.init(Scoped.get_scoped_conf(self._conf, extractor.get_scope()))
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/databuilder/extractor/athena_metadata_extractor.py", line 58, in init
    self._alchemy_extractor = sql_alchemy_extractor.from_surrounding_config(conf, self.sql_stmt)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/databuilder/extractor/sql_alchemy_extractor.py", line 102, in from_surrounding_config
    ae.init(c)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/databuilder/extractor/sql_alchemy_extractor.py", line 40, in init
    self._execute_query()
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/databuilder/extractor/sql_alchemy_extractor.py", line 65, in _execute_query
    self.results = self.connection.execute(self.extract_sql)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/pyathena/util.py", line 306, in _wrapper
    return wrapped(*args, **kwargs)
  File "/Users/patrickmckinley/git/onto/data-platform/anonymisation/scanner/.venv/lib/python3.8/site-packages/pyathena/cursor.py", line 81, in execute
    raise OperationalError(query_execution.state_change_reason)
sqlalchemy.exc.OperationalError: (pyathena.error.OperationalError) SYNTAX_ERROR: line 2:9: Column 'athena' cannot be resolved
[SQL:
    SELECT
        athena as cluster, table_schema as schema, table_name as name, column_name as col_name,
        data_type as col_type,ordinal_position as col_sort_order,
        comment as col_description, extra_info as extras from information_schema.columns

        ORDER by cluster, schema, name, col_sort_order ;
    ]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

As mentioned above - I've made a kludge to put that `{catalog_source}` in the query code in inverted commas so it comes through as a string literal and not a column reference - which i believe is the intention - and t least i'm unblocked with that :)

**Comment by vrajat** [comment]
*sigh* Sorry about that. I dont have access to athena right now and I havent been able to test it. I have added quotes now.

**Comment by patrick-mckinley** [comment]
haha, no worries. thanks for sorting that out 

I've been there myself a few times :)
